apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yml
  - service.yml
  - secret.yml

images:
  - name: chai-app
    newName: amitabhdevops/chai-devops
    newTag: latest

